default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: everydayrails_development

test:
  <<: *default
  username: <%= ENV["POSTGRES_USER"] || ENV["USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>
  host: <%= ENV["POSTGRES_PORT_5432_TCP_ADDR"] || "localhost" %>
  database: everydayrails_test

production:
  <<: *default
  database: everydayrails_production
  username: everydayrails
  password: <%= ENV['EVERYDAYRAILS_DATABASE_PASSWORD'] %>
