# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 008969042940ea15ff26aea3fc9ae74837e32be4046a2847d0178590904cb6b23bdc50025510e10ed4d66962450f8eecdee64d28b39ccc65f485a69230d6fa78

test:
  secret_key_base: 2020ca20e833c0d44719bed52683dccc1c87d71f6819196f44428af267a6d1663ddd7844e838b13bf7533f284a813a21b2fea9243879346622a86f459eb10844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
